image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - make test
      - step:
          name: Lint
          script:
            - pip install -r requirements-dev.txt
            - make black
            - make pycodestyle
            - make flake8
