version: '3.8'

services:
  db:
    image: postgis/postgis:13-master
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/install_database_test.sh:/docker-entrypoint-initdb.d/install_database_test.sh
    environment:
      POSTGRES_USER: autosa
      POSTGRES_DB: autosa
      POSTGRES_PASSWORD: autosa
    ports:
      - 5432:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data:
