[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.cache
  | \.pytest_cache
  | _build
  | buck-out
  | build
  | dist
  | tests/data
  | migrations
)/
'''
