# Generated by Django 3.2.12 on 2022-04-11 01:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='translation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.source'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['timestamp'], name='timestamp_idx'),
        ),
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.source'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
