# Generated by Django 3.2.12 on 2022-04-14 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220411_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='source',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='source',
            name='interface',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('telegram', 'Telegram'), ('website', 'Website'), ('api', 'API')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['origin'], name='origin_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['url'], name='url_idx'),
        ),
    ]
