# Generated by Django 3.2.12 on 2022-04-14 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220414_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, max_length=250, unique=True),
        ),
    ]
