# Generated by Django 3.2.12 on 2022-04-19 20:53

from django.db import migrations, models


def update_language_code(apps, schema_editor):
    Source = apps.get_model("api", "Source")
    Source.objects.filter(language="ua").update(language="uk")
    Translation = apps.get_model("api", "Translation")
    Translation.objects.filter(language="ua").update(language="uk")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220415_2116'),
    ]

    operations = [
        # keep old and new choices
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('ua', 'Ukrainian-old')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('ua', 'Ukrainian-old')], max_length=2),
        ),
        # update old data
        migrations.RunPython(update_language_code, reverse_code=migrations.RunPython.noop),
        # keep only new choices
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian')], max_length=2),
        ),
    ]
