# Generated by Django 3.2.12 on 2022-04-20 21:03

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20220419_2053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="location",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="translation",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="from_text",
            field=models.BooleanField(default=False),
        ),
    ]
