# Generated by Django 3.2.12 on 2022-04-26 22:24

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20220419_2053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="location",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="translation",
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="origin",
            field=models.CharField(
                choices=[
                    ("geotag", "Geotagged source"),
                    ("text", "Parsed from text"),
                    ("operator", "Geolocated by operator"),
                ],
                default="geotag",
                max_length=50,
            ),
        ),
    ]
